books/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('home/', views.get_home, name='home'),
    path('book/<int:id>', views.get_book, name='book'),
    path('register_book/', views.register_book, name='register_book'),
    path('create_category/', views.create_category, name='create_category'),
    path('create_borrowing/', views.create_borrowing, name='create_borrowing'),
    path('return_of_book/', views.return_of_book, name='return_of_book'),
    path('remove_book/<int:id>', views.remove_book, name='remove_book'),
    path('alter_book/<int:id>', views.alter_book, name='alter_book'),
    path('borrowings/', views.list_borrowings, name='borrowings'),
    path('process_ava/', views.process_ava, name='process_ava'),
]

clients/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.get_login, name='login'),
    path('valid_login/', views.valid_login, name='valid_login'),
    path('logout/', views.set_logout, name='logout'),
    path('register/', views.register_client, name='register'),
    path('valid_register/', views.valid_register, name='valid_register'),
    path('profile/', views.get_profile, name='profile'),
    path('upload-photo/', views.upload_photo_user, name='upload_photo'),
    path('profile-update/', views.update_name_email, name='update_datas'),
    path('change-password/', views.change_password, name='change_password'),
]

library_community/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/books/home')),
    path('books/', include('books.urls')),
    path('auth/', include('clients.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

clients/models.py
from django.db import models


class Client(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    password = models.CharField(max_length=64)
    photo = models.ImageField(upload_to='users', blank=True, null=True)

    def __str__(self):
        return self.name

clients/views.py
from django.shortcuts import render
from django.http import HttpResponse

from books.forms import BookForm, CategoryForm, BorrowingForm
from books.models import Book, Category
from .models import Client
from django.shortcuts import redirect
from hashlib import sha256


def get_login(request):
    if request.session.get('client'):
        return redirect('/books/home')
    status = request.GET.get('status')
    return render(request, 'login.html', {'status': status})


def valid_login(request):
    email = request.POST.get('email')
    password = request.POST.get('password')

    password = sha256(password.encode()).hexdigest()

    client = Client.objects.filter(email=email, password=password)

    if len(client) == 0:
        return redirect('/auth/login/?status=1')
    elif len(client) > 0:
        request.session['client'] = client[0].id
        return redirect('/books/home')

    return HttpResponse(f'{email} {password}')


def set_logout(request):
    request.session.flush()
    return redirect('/auth/login/')


def register_client(request):
    if request.session.get('client'):
        return redirect('/books/home')
    status = request.GET.get('status')
    return render(request, 'register.html', {'status': status})


def valid_register(request):
    name = request.POST.get('name')
    email = request.POST.get('email')
    password = request.POST.get('password')

    client = Client.objects.filter(email=email)

    if len(name.strip()) == 0 or len(email.strip()) == 0:
        return redirect('/auth/register/?status=1')

    if len(password) < 8:
        return redirect('/auth/register/?status=2')

    if len(client) > 0:
        return redirect('/auth/register/?status=3')

    try:
        password = sha256(password.encode()).hexdigest()
        client = Client(name=name, email=email, password=password)
        client.save()

        request.session['client'] = Client.objects.filter(email=email, password=password)[0].id

        return redirect('/books/home/?status=0')
    except:
        return redirect('/auth/register/?status=4')


def get_profile(request):
    client = Client.objects.get(id=request.session['client'])
    form_book, form_category, form_borrowing = BookForm(), CategoryForm(), BorrowingForm()

    form_category.fields['client'].initial = request.session['client']
    form_book.fields['client'].initial = request.session['client']

    form_book.fields['category'].queryset = Category.objects.filter(client=client)
    form_borrowing.fields['book'].queryset = Book.objects.filter(client=client, borrowed=False)
    form_borrowing.fields['responsible'].queryset = Client.objects.all()

    return render(request, 'profile.html', {'client': client,
                                            'client_logged_in': request.session.get('client'),
                                            'form_book': form_book,
                                            'form_category': form_category,
                                            'form_borrowing': form_borrowing})


def upload_photo_user(request):
    photo = request.FILES.get('photo')

    client = Client.objects.get(id=request.session['client'])

    client.photo = photo
    client.save()
    return redirect('/auth/profile/')


def update_name_email(request):
    new_name = request.POST.get('client_name')
    new_email = request.POST.get('client_email')

    client = Client.objects.get(id=request.session['client'])

    if client.name != new_name or client.email != new_email:
        if client.name != new_name:
            client.name = new_name

        if client.email != new_email:
            client.email = new_email

        client.save()

    # else:
        # alert by same datas, no update

    return redirect('/auth/profile/')


def change_password(request):
    new_password = sha256(request.POST.get('client_password').encode()).hexdigest()
    password_again = sha256(request.POST.get('client_password_again').encode()).hexdigest()

    given_password = sha256(request.POST.get('client_current_password').encode()).hexdigest()

    client = Client.objects.get(id=request.session['client'])

    if client.password == given_password:
        if new_password == password_again:
            client.password = new_password
            client.save()
            return redirect('/auth/profile/')
        else:
            return HttpResponse('your passwords are not equals')
    else:
        return HttpResponse('this is not the password')

clients/templates/login.html
{% extends 'base.html' %}

{% block 'title' %} Login {% endblock %}

{% block 'content' %}

<div class="container" xmlns="http://www.w3.org/1999/html">
    <br>
    {% if status == '1' %}
        <div class="alert alert-primary alert-dismissible fade show" role="alert">
            Invalid e-mail or password.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    {% if status == '2' %}
        <div class="alert alert-primary alert-dismissible fade show" role="alert">
            Log in before trying to enter on the system.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md">
            <h1>Login</h1>
            <hr>
            <form method="POST" action="{% url 'valid_login' %}">{% csrf_token %}
                <label for="email">E-mail</label>
                <input name="email" class="form-control" type="email" placeholder="e-mail">
                <br>
                <label for="password">Senha</label>
                <input name="password" class="form-control" type="password" placeholder="senha">
                <br>
                <div class="row">
                    <input class="btn btn-info btn-lg mx-auto" type="submit" value="Entrar">
                </div>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
    <hr>
    <p class="text-center">
        <a href="{% url 'register' %}">Criar conta</a>
    </p>
</div>

{% endblock %}

clients/templates/profile.html
{% extends 'base.html' %}

{% block 'title' %} {{client.name}} {% endblock %}

{% block 'head' %}
    <style>
        .user img{
            margin:1rem 0;
            border-radius: 50%;
            height: 15rem;
            width: 15rem;
        }
    </style>

{% endblock %}

{% block 'content' %}

    <div class="container">
        <br>
        {% if client.photo %}
        <div class="user">
            <img src="{{ client.photo.url }}" class="mx-auto d-block" alt="..." data-toggle="modal" data-target="#photoModal">
        </div>
        {% else %}
            <div style="border-radius: 50%; height: 15rem; width: 15rem; background-color: gray; margin: auto;" data-toggle="modal" data-target="#photoModal"></div>
            <br>
        {% endif %}
        <h1 class="text-center">{{ client }}</h1>

        <hr>

        <form style="max-width: 500px; margin: auto;" action="{% url 'update_datas' %}" method="POST">{% csrf_token %}
            <p>
                <label>Nome: </label>
                <input class="form-control" type="text" value="{{ client.name }}" name="client_name" required>
            </p>
            <p>
                <label>E-mail: </label>
                <input class="form-control" type="email" value="{{ client.email }}" name="client_email" required>
            </p>
            <div class="row">
                <div class="col-md-12 bg-light text-right">
                    <input type="submit" class="btn btn-success" value="Salvar">
                </div>
            </div>
        </form>

        <hr>

        <button type="button" class="btn btn-primary mx-auto d-block" data-toggle="modal" data-target="#passwordModal">
          Alterar Senha
        </button>

        <br><br>

        <div class="modal fade" id="photoModal" tabindex="-1" role="dialog" aria-labelledby="photoModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="photoModalLabel">Upload de Foto</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form action="{% url 'upload_photo' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <div class="form-group">
                        <label for="id_photo">Photo:&nbsp;</label>
                        <input class="form-control" type="file" name="photo" id="id_photo" required>
                    </div>
                    <input type="submit" class="btn btn-success" value="Save">
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="modal fade" id="passwordModal" tabindex="-1" role="dialog" aria-labelledby="passwordModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="passwordModalLabel">Alteração de Senha</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                  <form action="{% url 'change_password' %}" method="POST">{% csrf_token %}
                      <p>
                        <label>Nova Senha: </label>
                        <input class="form-control" type="password" name="client_password">
                      </p>
                      <p>
                        <label>Repita Nova Senha: </label>
                        <input class="form-control" type="password" name="client_password_again">
                      </p>
                      <p>
                        <label>Atual Senha: </label>
                        <input class="form-control" type="password" name="client_current_password">
                      </p>
                      <div class="row">
                        <div class="col-md-12 bg-light text-right">
                            <input type="submit" value="Salvar" class="btn btn-primary">
                        </div>
                      </div>
                  </form>
              </div>
            </div>
          </div>
        </div>
    </div>

{% endblock %}

clients/templates/register.html
{% extends 'base.html' %}

{% block 'title' %} Register {% endblock %}

{% block 'content' %}

<div class="container" xmlns="http://www.w3.org/1999/html">
    <br>


    {% if status == '1' %}
        <div class="alert alert-primary alert-dismissible fade show" role="alert">
            The fields <strong>name</strong> or <strong>email</strong> cannot be void.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    {% if status == '2' %}
        <div class="alert alert-primary alert-dismissible fade show" role="alert">
            The field <strong>password</strong> must have 8 characters at least.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    {% if status == '3' %}
        <div class="alert alert-primary alert-dismissible fade show" role="alert">
            This <strong>user</strong> already exist in the system.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    {% if status == '4' %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>ERROR IN THE SYSTEM!</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md">
            <h1>Criar Conta</h1>
            <hr>
            <form method="POST" action="{% url 'valid_register' %}">{% csrf_token %}
                <label for="name">Nome Completo</label>
                <input name="name" class="form-control" type="text" placeholder="nome">
                <br>
                <label for="email">E-mail</label>
                <input name="email" class="form-control" type="email" placeholder="e-mail">
                <br>
                <label for="password">Senha</label>
                <input name="password" class="form-control" type="password" placeholder="senha">
                <br>
                <div class="row">
                    <input class="btn btn-info btn-lg mx-auto" type="submit" value="Cadastrar">
                </div>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
    <hr>
    <p class="text-center">
        <a href="{% url 'login' %}">Login</a>
    </p>
</div>

{% endblock %}