books/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('home/', views.get_home, name='home'),
    path('book/<int:id>', views.get_book, name='book'),
    path('register_book/', views.register_book, name='register_book'),
    path('create_category/', views.create_category, name='create_category'),
    path('create_borrowing/', views.create_borrowing, name='create_borrowing'),
    path('return_of_book/', views.return_of_book, name='return_of_book'),
    path('remove_book/<int:id>', views.remove_book, name='remove_book'),
    path('alter_book/<int:id>', views.alter_book, name='alter_book'),
    path('borrowings/', views.list_borrowings, name='borrowings'),
    path('process_ava/', views.process_ava, name='process_ava'),
]

library_community/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/books/home')),
    path('books/', include('books.urls')),
    path('auth/', include('clients.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

books/models.py
from django.db import models
from datetime import date, datetime
from clients.models import Client


class Category(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField()
    client = models.ForeignKey(Client, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Categorie'


class Book(models.Model):
    img = models.ImageField(upload_to='capa')
    name = models.CharField(max_length=100)
    auth = models.CharField(max_length=30)
    cd_auth = models.CharField(max_length=30, blank=True, null=True)
    register_date = models.DateField(default=date.today)
    borrowed = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Borrowing(models.Model):
    choices = (
        ('B', 'Bad'),
        ('R', 'Regular'),
        ('G', 'Good'),
        ('A', 'Awesome')
    )
    responsible = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True, null=True)
    anonymous_responsible = models.CharField(max_length=30, blank=True, null=True)
    borrowing_date = models.DateTimeField(default=datetime.now())
    book_return = models.DateTimeField(blank=True, null=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    available = models.CharField(max_length=1, choices=choices, blank=True, null=True)

    def __str__(self) -> str:
        return f'{self.responsible} | {self.book}'

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block 'head' %} {% endblock %}
    <title>{% block 'title' %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'home' %}">Library Community</a>
      {% if client_logged_in %}
        <div class="dropdown show">
          <a class="btn btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true">
            Menu
          </a>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
            {% if client.photo %}
              <div class="user">
                  <img style="margin:1rem 0; border-radius: 50%; height: 7rem; width: 7rem;" src="{{ client.photo.url }}" class="mx-auto d-block" alt="..." data-toggle="modal" data-target="#photoModal">
              </div>
            {% else %}
              <div style="border-radius: 50%; height: 7rem; width: 7rem; background-color: gray; margin: auto;"></div>
            {% endif %}
            <a class="dropdown-item text-center" href="{% url 'profile' %}">Profile</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item text-center">Total de {{ books_tot }} Livros</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item text-center" href="#" data-toggle="modal" data-target="#formsModal">Panel de Cadastro</a>
            <a class="dropdown-item text-center" href="{% url 'borrowings' %}">Ver Meus Empréstimos</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item text-center" href="{% url 'logout' %}">Sair</a>
          </div>
        </div>
      {% endif %}
    </nav>

    {% block 'content' %} {% endblock %}

    {% if client_logged_in %}
      <div class="modal fade" id="formsModal" tabindex="-1" role="dialog" aria-labelledby="formsModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="formsModalLabel">Formulários de Cadastro</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body mx-auto">
              <button onclick="show_form(1)" class="btn btn-info">CATERGORIA</button>
              <button onclick="show_form(2)" class="btn btn-info">LIVRO</button>
              <button onclick="show_form(3)" class="btn btn-info">EMPRÉSTIMO</button>
              <br><br>
              <hr>

              <div style="display: none;" id="book">
                <form action="{% url 'register_book' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                  <div class="form-group">
                    <label for="id_name">Título:&nbsp;</label>
                    {{ form_book.name }}
                  </div>
                  <div class="form-group">
                    <label for="id_auth">Autor:&nbsp;</label>
                    {{ form_book.auth }}
                  </div>
                  <div class="form-group">
                    <label for="id_img">Capa:&nbsp;</label>
                    {{ form_book.img }}
                  </div>
                  <div class="form-group">
                    <label for="id_cd_auth">Co-Autor:&nbsp;</label>
                    {{ form_book.cd_auth }}
                  </div>
                  <div class="form-group">
                    <label for="id_category">Categoria:&nbsp;</label>
                    {{ form_book.category }}
                  </div>

                  {{ form_book.register_date }}
                  {{ form_book.borrowed }}
                  {{ form_book.client }}

                  <input type="submit" class="btn btn-success" value="Salvar">
                </form>
              </div>

              <div style="display: none;" id="category">
                <form action="{% url 'create_category' %}" method="POST">{% csrf_token %}
                  <div class="form-group">
                    <label for="id_name">Categoria:&nbsp;</label>
                    {{ form_category.name }}
                  </div>
                  <div class="form-group">
                    <label for="id_description">Descrição:&nbsp;</label>
                    {{ form_category.description }}
                  </div>

                  {{ form_category.client }}

                  <input type="submit" class="btn btn-success" value="Salvar">
                </form>
              </div>

              <div style="display: none;" id="borrowing">
                <form action="{% url 'create_borrowing' %}" method="POST">{% csrf_token %}
                  <div style="display: block;" id="responsible" class="form-group">
                    <label for="id_responsible">Responsável:&nbsp;</label>
                    {{ form_borrowing.responsible }}
                    <p class="text-right">
                      <a onclick="change_responsible_type()" href="#">mudar para usuário anônimo</a>
                    </p>
                  </div>
                  <div style="display: none;" id="anonymous_responsible" class="form-group">
                    <label for="id_anonymous_responsible">Responsável Anônimo:&nbsp;</label>
                    {{ form_borrowing.anonymous_responsible }}
                    <p class="text-right">
                      <a onclick="change_responsible_type()" href="#">mudar para usuário do sistema</a>
                    </p>
                  </div>
                  <div class="form-group">
                    <label for="id_borrowing_date">Data de Empréstimo:&nbsp;</label>
                    {{ form_borrowing.borrowing_date }}
                  </div>
                  <div class="form-group">
                    <label for="id_book">Livro:&nbsp;</label>
                    {{ form_borrowing.book }}
                  </div>

                  {{ form_borrowing.book_return }}
                  {{ form_borrowing.available }}
                  <input type="submit" class="btn btn-success" value="Salvar">
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endif %}

    <script>
      function change_responsible_type(){
        responsible = document.getElementById('responsible')
        anonymous_responsible = document.getElementById('anonymous_responsible')

        if (responsible.style.display == 'block'){
          responsible.style.display = 'none'
          anonymous_responsible.style.display = 'block'
        } else {
          responsible.style.display = 'block'
          anonymous_responsible.style.display = 'none'
        }
      }

      function show_form(c){
        category = document.getElementById('category')
        book = document.getElementById('book')
        borrowing = document.getElementById('borrowing')

        if(c == 1){
          category.style.display = 'block';
          book.style.display = 'none';
          borrowing.style.display = 'none';
        }else if(c == 2){
          category.style.display = 'none';
          book.style.display = 'block';
          borrowing.style.display = 'none';
        }else if(c == 3){
          category.style.display = 'none';
          book.style.display = 'none';
          borrowing.style.display = 'block';
        }
      }
    </script>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
  </body>
</html>